---
layout: page
title: Fields
---

Fields in Nabu use a **type-after-name** syntax, similar to Kotlin.

```java
public class Person {
    private firstName : String;
    private lastName : String;
}
```

Fields can be `final`:

```java
public class Box<T> {
    private final value: T;

    public Box(value: T) {
        this.value = value;
    }
}
```

Field initialization code is generated by the `Lower` phase, both in constructors and in the static initializer.
