<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.potjerodekool</groupId>
        <artifactId>nabu-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>native-backend</artifactId>
    <name>${project.groupId}:${project.artifactId}</name>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <bytedeco.version>21.1.8-1.5.13</bytedeco.version>
        <javacpp.verion>1.5.13</javacpp.verion>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.github.potjerodekool</groupId>
            <artifactId>nabu-compiler</artifactId>
            <version>0.1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <!-- For native backend -->

        <!--
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>${javacpp.verion}</version>
        </dependency>
        -->

        <!--
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>llvm</artifactId>
            <version>${bytedeco.version}</version>
        </dependency>
        -->

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>llvm-platform</artifactId>
            <version>${bytedeco.version}</version>
            <scope>provided</scope>
        </dependency>

        <!--
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>libffi-platform</artifactId>
            <version>3.5.2-1.5.13</version>
        </dependency>
        -->

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>